myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('',include('shop.urls',namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name= 'shop'

urlpatterns = [
    path('',views.home,name='home'),
    path('products/',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)


    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                related_name='products',
                                on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])
        

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)


    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

    

myshop/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True})
    return render(request, 'cart/detail.html',{'cart':cart})

    

myshop/shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm

# Create your views here.
def home(request):
    return render(request,'home.html')


def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = products.filter(category=category)
    
    return render(request,
                'shop/product/list.html',
                {'category': category,
                'categories': categories,
                'products': products})

def product_detail(request, id, slug):
    
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                'shop/product/detail.html',
                {'product': product,
                'cart_product_form':cart_product_form})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html"%}
{% load static %}

{% block title%}
    Your shopping cart
{% endblock %}

{% block content%}
    <h1 class="cart_title">Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{product.get_absolute_url}}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png"%}{% endif %}">

                            </a>
                        </td>
                        <td>{{product.name}}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{item.update_quantity_form.quantity}}
                                {{item.update_quantity_form.override}}
                                <input type="submit" value="Update">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                <input type="submit" value="Remove">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">${{item.price}}</td>
                        <td class="num">${{item.total_price}}</td>
                    </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="num">${{cart.get_total_price}}</td>
                </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock%}

myshop/shop/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
        <title>North korea</title>
    </head>
    <body>
        <div class="home_page" id="home_page_container">
            <div class="logo-container">
                <img class="logo" src="{% static 'images/logo.png'%}">
            </div>
            <div class="home">
                <div class="primary-title-container">
                    <h1 class="primary-title" id="primary-title">Strong and Prosperous Nation</h1>
                </div>
                <a class="primary-button" href="{% url 'shop:product_list' %}" onmouseover="mouseOn()" onmouseleave="mouseOff()">Enter Market</a>
            </div>
        </div>
        <script>
            var primary_title = document.getElementById('primary-title');
            var background_image = document.getElementById('home_page_container');
            
            function mouseOn() {
                primary_title.innerHTML = "Peasant, Plead on your knees to our great leader Kim Jong Un";
                background_image.className= 'warning_page';
            }
            function mouseOff() {
                primary_title.innerHTML = "Strong and Prosperous Nation";
                background_image.className = 'home_page';
            }

        </script>
    </body>
</html>

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{%endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        <link href="{% static "css/list.css" %}" rel="stylesheet">
        <link href="{% static "css/detail.css" %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <div id="header">
            <a href="{% url 'shop:product_list'%}" class="logo">North korea</a>
            {% with total_items=cart|length %}
                {% if total_items > 0%}

                <a class="shopping-cart-logo" href="{% url 'cart:cart_detail' %}">
                    <h3>
                        <i class="fa fa-shopping-cart"></i>
                        {{total_items}} item{{total_items|pluralize}}, ${{cart.get_total_price}}
                    </h3>
                </a>
                {% else %}
                <h3 class="shopping-cart-logo">
                    Your cart is empty
                </h3>
                {% endif %}
            {% endwith %}
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img class="product_image" src="{% if product.image %}{{ product.image.url}}{% else %}{% static "images/no_image.png"%}{% endif %}">
        <div class="product_description">
            <h1 class="product_name">{{product.name}}</h1>
            <a class="product_category" href="{{ product.category.get_absolute_url}}">
                {{product.category}}
            </a>
            <p class="product_price">${{product.price}}</p>
            <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{cart_product_form}}
                {%csrf_token%}
                <input type="submit" value="Add to cart">
            </form>
            {{product.description|linebreaks}}
        </div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{category.name}}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div class="product_container">
        <div id="sidebar">
            <h1>Categories</h1>
            <ul>
                <li {% if not category %}class="selected"{%endif%}>
                    <a href="{% url "shop:product_list" %}">All</a>
                </li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{c.get_absolute_url}}">{{c.name}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div id="main" class="product_list">
            <h1 class="main_product_category">{% if category %}{{category.name}}{% else %}products{% endif %}</h1>
            <div class="items-container">
                {% for product in products %}
                    <div class="item">
                        <a href="{{product.get_absolute_url }}" >
                            <img class="item-image-container" src="{% if product.image %}{{product.image.url}}{% else %}{% static "images/no_image.png" %}{%endif %}">
                        </a>
                        <a class="item_name_text" href="{{product.get_absolute_url}}">{{product.name}}</a>
                        <br>
                        <span class="item_price_text">${{product.price}}</span>
                    </div>
                {%endfor%}
            </div>
        </div>
    </div>
    <script>
        const productElement = document.getElementById('main').querySelectorAll('.item')
        productElement.forEach(product => {
            product.addEventListener('mouseover',showCard)
            product.addEventListener('mouseleave',blurCard)
        })

        function showCard() {
            this.classList.add('active')
        }
        function blurCard() {
            this.classList.remove('active')
        }

    </script>
{% endblock %}